language: python
python:
    - "3.7"
services:
  - postgresql

install:
  - pip install -r requirements.txt


script:
  - coverage run --source='eha' manage.py test && coverage report

after_success:
  - coveralls